### ISSUE TITLE
Abandon Django 1.4-1.6 support

### ISSUE THREAD

**Issue by yangyubo** [django-notifications/django-notifications#89]
According to [here](https://www.djangoproject.com/download/), Django already officially stops support version lower than 1.8, and no longer provides security updates or bug fixes.

I think it's time to at least abandon Django 1.4-1.6 support.

@LegoStormtroopr , @zhang-z what are your thoughts?

**Comment by zhang-z** [comment]
It sounds good to me. In that case, we can remove "south_migrations" as well :)
Maybe we can bump a version and mark it as last supported version for Django 1.4-1.6

**Comment by LegoStormtroopr** [comment]
:+1: Sounds like a good plan. 1.6 is now well out of support, and as @zhang-z says it means we can drop south support too. Perhaps after PR #83 is in we can bump version number consider that the last 1.6 release.

**Comment by LegoStormtroopr** [comment]
This also means we can drop Python 2.6 from testing as well - [from Django 1.7 release notes](https://docs.djangoproject.com/en/1.9/releases/1.7/)
> Since Django 1.6, support for Python 2.6 has been dropped and support for Python 3.4 has been added.

But should add Python 3.5 testing in: [from Django 1.9 release notes](https://docs.djangoproject.com/en/1.9/releases/1.9/):
> Django 1.9 requires Python 2.7, 3.4, or 3.5. We highly recommend and only officially support the latest release of each series.

**Comment by yangyubo** [comment]
Thank you guys. OK, I'll release version as soon as @LegoStormtroopr closed #83 , and mark it as the last Django 1.4-1.6 compatible version.

As a summary, here are the next tasks:

- [ ] Merge and close PR #83 ( @LegoStormtroopr )
- [ ] Release last Django 1.4-1.6 compatible version ( @yangyubo )
- [ ] (*) Remove "south_migrations" dependence
- [ ] (*) Make django-notification compatible with django-model-utils >= 2.4 ( #87, #88, #90 )
- [ ] Update ".travis.yml" and make sure compatible with Django 1.9 and Python 3.5, and drop Python 2.6 from testing ( @LegoStormtroopr )
- [ ] Update README, setup.py, Changelog to reflect changes ( @yangyubo )
- [ ] Release the first Django 1.7+ required version ( @yangyubo )

Any other supplements?

@zhang-z Do you have time to take on two tasks with (*) marked?

**Comment by zhang-z** [comment]
No prob. Probably by this weekend.

**Comment by yangyubo** [comment]
Great, thank you @zhang-z

**Comment by zhang-z** [comment]
Created a pull request #91 into branch "drop-support-django1.6"

**Comment by illing2005** [comment]
:+1: 
Does your pull request also add support for django1.9?

**Comment by zhang-z** [comment]
@illing2005 , it doesn't support Django 1.9 yet. I tried but found some incompatibilities. In Django 1.9, "import a Model in \__init__.py" will raise ```django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet```. "notifications/\__init__.py" and "notifications/tests/\__init__.py" both have this issue. Welcome to contribute to it in branch "django-notifications:drop-support-django1.6" :)  I will also check it if I find some free time.

**Comment by illing2005** [comment]
I created a pull request for Django 1.9 compability (#94)

**Comment by zhang-z** [comment]
@illing2005 , merged. Thanks for the contribution!

**Comment by yangyubo** [comment]
@zhang-z @LegoStormtroopr , since #83 has got fixed, I'm going to release the last Django 1.4~1.6 compatible major version, tag it "0.8.0" and only accept bug-fixes in 0.8.x branch.

**Comment by LennyLip** [comment]
@illing2005 pull does not work with django 1.8.3

i use notifiy in a custom app view :

    from notifications import notify
    ImportError: cannot import name 'notify'

so, changed to this and its work for me.

    from django.apps import AppConfig
    import notifications.signals

    class Config(AppConfig):
        name = "notifications"
        notifications.notify = notifications.signals.notify

2 all. btw, in init.py

    try:		
         from notifications.urls import urlpatterns		
         urls = (urlpatterns, 'notifications', 'notifications')		
    except ImportError:		
         pass

was ugly. It was call url.py, then view.py and model.py in first step of Initializing the application registry, but models must to be initialized on second stage (see https://docs.djangoproject.com/en/1.9/ref/applications/#how-applications-are-loaded )

**Comment by yangyubo** [comment]
django-notifications-hq 0.8.0 [has been released!](https://pypi.python.org/pypi/django-notifications-hq/0.8.0)

Branch 0.8.x also created to hold bugfixes.

@zhang-z please go ahead, it's your turns now 😬

**Comment by zhang-z** [comment]
@yangyubo , I fixed conflicts and created pull request #101 . Would you like to review the code before merging into master?

**Comment by yangyubo** [comment]
@zhang-z No problem, will update you next day.

**Comment by zhang-z** [comment]
@yangyubo & @LegoStormtroopr , seems no major issues in the current master branch. Do you think it's time to bump the first Django1.9 supported version?

**Comment by yangyubo** [comment]
Happy new year to all ! 🎉

@zhang-z you have done a tremendous job, I'll do some basic confirmation in the next few days, and then publish the brand new release.

**Comment by LegoStormtroopr** [comment]
:+1:

**Comment by yangyubo** [comment]
@zhang-z @LegoStormtroopr This brand new version [was released](https://pypi.python.org/pypi/django-notifications-hq/1.0) at the beginning of 2016!
And I hope you don't mind that I marked release 1.0 😬

Full changelog in here: #115 

Happy new year 🎉!

**Comment by zhang-z** [comment]
Awesome!! And happy new year :)
