### ISSUE TITLE
Does not work in Django 2.1

### ISSUE THREAD

**Issue by belal-bh** [django-notifications/django-notifications#251]
I know it's `dependency` that it supports `Django 2.0` ( that does not mean it will also support `Django 2.1` )  but I think it's time to update it to support the latest version of Django.

I just `cloned` and want to `makemigrations`  but I've got error which is ( at the end of line):
```
File "C:\Users\env\projects\django-notifications\notifications\tests\urls.py", line 7, in <module>
    from django.contrib.auth.views import login
ImportError: cannot import name 'login'
```

My installed Django version... 
```
Django==2.1
django-model-utils==3.1.2
django-notifications-hq==1.5.0
jsonfield==2.0.2
pytz==2018.9
```
Thanks

**Comment by abijoy** [comment]
from django 2.1 the function based auth views, login & logout are replaced by class based LoginView & LogoutView

**Comment by ehmadzubair** [comment]
@belal-bh @abijoy https://github.com/django-notifications/django-notifications/pull/253

**Comment by ehmadzubair** [comment]
This should be closed.

@yangyubo
